#!/usr/bin/env bash
#!/usr/bin/env ruby
source "https://rubygems.org"

gem "jekyll"
gem "html-proofer"

require 'html/proofer'

set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproof ./_site
